### ISSUE TITLE
Leak issue

### ISSUE THREAD

**Issue by kamvoick** [mgacy/MVVMC-SplitViewController#1]
Hello, first of all thank you for this "template", it's been very useful for me, but there is one issue with memory leak/retains. TabBarCoordinator did not deallocate at all with its descendants, when i'm loggin out it stays in memory, and loggin back create TabBarCoordinator again and again. I'm trying to figured it out but no clue at this point, any help? Thanks

**Comment by kamvoick** [comment]
found the solution, tabbar should take(1) coordinatorResult to deallocate

**Comment by mgacy** [comment]
Thanks!
