### ISSUE TITLE
Migrating from Storyboard to view code

### ISSUE THREAD

**Issue by alchemistgo87** [mgacy/MVVMC-SplitViewController#2]
Hi @mgacy 

Can you please help me with the migration from Storyboard to the view code. In the Reusable.swift file, how should I modify the instance() and instantiateViewController<T: UIViewController>() functions to migrate from using storyboard to using view code.

Thank you

**Comment by mgacy** [comment]
You actually wouldn't need to modify `Reusable.swift`, just the view controllers and the coordinators responsible for instantiating them. For example, to convert the Login scene to use view code, you would need to make the following changes in `LoginViewController.swift`:

- replace all the `@IBOutlet`s
- make `bindings` a lazy var
- add `init()` and `init?(coder:)`
- add these subviews in `setupView()` and configure your constraints

The modified file would look something like the following:

```swift
class LoginViewController: UIViewController, ViewModelAttaching {

    var viewModel: Attachable<LoginViewModel>!
    lazy var bindings: LoginViewModel.Bindings = {
        return LoginViewModel.Bindings(
            username: loginTextField.rx.text.orEmpty.asDriver(),
            password: passwordTextField.rx.text.orEmpty.asDriver(),
            loginTaps: loginButton.rx.tap.asDriver(),
            signupTaps: signupButton.rx.tap.asDriver(),
            doneTaps: passwordTextField.rx.controlEvent(.editingDidEndOnExit).asDriver(),
            cancelTaps: cancelButtonItem.rx.tap.asDriver()
        )
    }()

    let disposeBag = DisposeBag()

    // MARK: Interface

    let loginTextField: UITextField = {
        let view = UITextField()
        // other properties ...
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

    // ...
    
    // MARK: - Lifecycle

    init() {
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // ...

}
```

Then, in `LoginCoordinator.swift` you would use `let viewController = LoginViewController()`.

I would also suggest taking a look at [this](https://www.thomasvisser.me/2017/02/09/mvvm-rx/) excellent post by Thomas Visser for an explanation of `Attachable<ViewModel>`.

**Comment by alchemistgo87** [comment]
Thank you so much for this detailed explanation @mgacy.

In this, do we really need to add init() and init?(coder:), if we are not using storyboard at all?

**Comment by mgacy** [comment]
Good catch; we don't. We would need to implement `init?(coder:)` if we were using a custom initializer to inject dependencies, for example, but not here.

**Comment by alchemistgo87** [comment]
Alright. Thanks again @mgacy for your time and help.
