### ISSUE TITLE
Reacting on events from other coordinator

### ISSUE THREAD

**Issue by kamvoick** [mgacy/MVVMC-SplitViewController#4]
Hello, i'm back to this project after some time but have question about reacting between coordinators. How would you solve situation when i have my button clicked on some Coordinator1(VC-button > binded to viewModel), and i'd like to refresh let's say counting by +1 on another coordinator Coordinator2(VC-countingLabel > binded to viewModel)? This is first case, second one is when coordinators are deeper nested for example: Coordinator1 and Coordinator4 (1/2, 1/4 are nesting levels). So my only ideas are: via dependency, delegates (not the best option i suppose). 
Thanks for any reply :)

**Comment by mgacy** [comment]
First, apologies if I miss something obvious, but I've been working outside of RxSwift lately (just to diversify my portfolio).

I would approach this using dependency injection and the state container pattern. Take a look at some of these libraries for inspiration, if not a solution:

- [ReSwift](https://github.com/ReSwift/ReSwift)
- [ReactorKit](https://github.com/ReactorKit/ReactorKit)
- [RxFeedback](https://github.com/NoTests/RxFeedback.swift)
- [RxReduce](https://github.com/RxSwiftCommunity/RxReduce)

It sounds like the events you want to share are not related to navigation and thus not really the business of the coordinators beyond being part of a dependency to be shared. Using something like one of the above libraries, I would define a `CounterStore` (or Reactor or whatever you want to call it) and the corresponding protocols for `AppDependency` and inject them there.
