### ISSUE TITLE
Leak issue of SignUpViewController

### ISSUE THREAD

**Issue by 89gnahT** [mgacy/MVVMC-SplitViewController#6]
Hi, thanks for a good example of MVVM-C architecture. However, in this demo, the SignUpViewController instance of the SignUpCoordinator did not deallocate when present/dismiss from the LoginCoordinator.
![Screen Shot 2020-09-14 at 17 11 17](https://user-images.githubusercontent.com/39072173/93073682-833fe800-f6ad-11ea-990d-029d41b690dd.png)

**Comment by mgacy** [comment]
Thank you for bringing this to my attention
